services:
  - type: web
    name: automatte-nanobot
    runtime: docker
    plan: free
    region: singapore
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: NANOBOT_MODEL
        value: "minimaxai/minimax-m2.7" # Switched to MiniMax for speed
      - key: RCLONE_CONFIG_BASE64
        sync: false
      - key: PORT
        value: "10000"